# services:
#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#     depends_on:
#       - mlflow
#     environment:
#       - MLFLOW_TRACKING_URI=http://mlflow:5000
#       - HF_TOKEN=${HF_TOKEN}

#   mlflow:
#     image: ghcr.io/mlflow/mlflow:latest
#     ports:
#       - "5056:5000"
#     environment:
#       - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
#     command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow
#     volumes:
#       - ./mlruns:/mlflow

#   prometheus:
#     image: prom/prometheus
#     ports:
#       - "9090:9090"
#     volumes:
#       - ./prometheus.yml:/etc/prometheus/prometheus.yml

#   grafana:
#     image: grafana/grafana
#     ports:
#       - "3000:3000"
#     volumes:
#       - grafana-storage:/var/lib/grafana

# volumes:
#   grafana-storage:


services:
  app:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000  # Add this for inter-container communication
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - HF_TOKEN=${HF_TOKEN}
      - FLASK_DEBUG=false  # Disable Flask debug mode

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5056:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow
    volumes:
      - ./mlruns:/mlflow

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    # Remove Docker socket mount

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: